export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE'
export const REMOVE_ATTRIBUTE = 'REMOVE_ATTRIBUTE'
export const SET_ATTRIBUTES = 'SET_ATTRIBUTES'
export const FETCH_ATTRIBUTES_FAILED = 'FETCH_ATTRIBUTES_FAILED'

export const SAVE_KINDRED_START = 'SAVE_KINDRED_START'
export const SAVE_KINDRED_SUCCESS = 'SAVE_KINDRED_SUCCESS'
export const SAVE_KINDRED_FAILED = 'SAVE_KINDRED_FAILED'