const skills = [
  {
    label: "Athletics",
    type: "ath",
    val: [
      "• You were always attentive in gym class and you still have a spring in your step.",
      "•• Despite being dead, you are still as fit as a mortal doing regular exercise.",
      "••• You are fit as a fiddle and could play professional sports. Night games, at least.",
      "•••• With your parkour abilities, why would you need to turn into a bat?",
      "••••• Olympic records await you; only a very few peak humans can achieve what you can. Vampires mistake your skill for Physical Disciplines.",
    ],
  },
  {
    label: "Brawl",
    type: "bra",
    val: [
      "• You had a tough upbringing and had to fight to justify your place. You still have some moves.",
      "•• You received some training in hitting someone hard and accurately.",
      "••• You more than hold your own in a scrap.",
      "•••• You either received Spetsnaz quality training, or you have spent decades of afterlife in fights.",
      "••••• You could win MMA championships even without the use of your vampiric powers.",
    ],
  },
  {
    label: "Craft",
    type: "cra",
    val: [
      "• You are an amateur, but you know what you are doing.",
      "•• Your craftsmanship is admired for its functionality.",
      "••• Your creations can be beautiful or horrifying, but their intent always clear.",
      "•••• Your skill is highly respected among the kine and Kindred aware of it.",
      "••••• You are often chosen to create the focal point for parties at Elysium.",
    ],
  },
  {
    label: "Drive",
    type: "dri",
    val: [
      "• You are a cautious driver, unlikely to make any mistakes.",
      "•• You can put your foot down without much fear of an accident, providing visibility is good.",
      "••• You have won car chases, earning a cool reputation among the Anarchs.",
      "•••• You could be a stunt driver or the personal chauffeur of a Prince or Baron.",
      "••••• You know cars inside and out. Few can match your skill and knowledge.",
    ],
  },
  {
    label: "Firearms",
    type: "fir",
    val: [
      "• You’ve fired a gun a few times, at the range or in less-formal circumstances.",
      "•• You know (and know how) to keep your weapon clean, take it apart, and reassemble it.",
      "••• You’ve been in the shit (“seen the elephant” if you’re older than a century) and come out the other side.",
      "•••• You can handle trick shots, called shots, running shots – really anything ending in a gunshot.",
      "••••• You’ve been practicing since the debut of the Winchester.",
    ],
  },
  {
    label: "Larceny",
    type: "lar",
    val: [
      "• You can pick a simple lock or a careless pocket.",
      "•• You can hotwire a car or shoplift with ease.",
      "••• You can identify the locations of security cameras and alarms so to best bypass them.",
      "•••• You can defeat a keypad, re-tool an ID card, or crack a safe.",
      "••••• You can get into – or out of – the vault of a multinational bank.",
    ],
  },
  {
    label: "Melee",
    type: "mel",
    val: [
      "• You can swing a bat or blade and mostly hit the people you intend to.",
      "•• Your clear competence with a weapon in hand should give attackers pause.",
      "••• Your skill with a melee weapon is known throughout the domain.",
      "•••• The fools brought a gun to your knife fight.",
      "••••• You are the domain’s weaponmaster, sought out by Kindred far and wide for your skill.",
    ],
  },
  {
    label: "Stealth",
    type: "ste",
    val: [
      "• Spotting you under the cover of darkness or in camouflage proves difficult.",
      "•• You can sneak by casual observers and stalk unknowing victims without raising any hackles.",
      "••• You evade patrolling guards, moving softly and hiding easily.",
      "•••• Your subtle, silent passage could make you a worthy ninja – or a worthy foe for ninja.",
      "••••• The Children of Haqim come to you for advice on stalking and hiding, if they can find you.",
    ],
  },
  {
    label: "Survival",
    type: "sur",
    val: [
      "• You know the trails and wilderness around your domain.",
      "•• You spend more time outdoors than inside, and you can track anyone who doesn’t possess woodcraft.",
      "••• You can subsist outside the city, setting traps for mortals and a shelter for yourself.",
      "•••• You can thrive outside the city like the true predator you are.",
      "••••• Gangrel run in packs with you – if they can keep up.",
    ],
  },
  {
    label: "Animal Ken",
    type: "ani",
    val: [
      "• Animals shy away from you but will not bolt or snap.",
      "•• Animals are docile around you, acting as if you aren’t there, unless you build a rapport with them.",
      "••• Animals treat you as if you were a warm, friendly owner, unless provoked to do otherwise.",
      "•••• You draw animals into your orbit. Few attacking creatures maintain their aggression.",
      "••••• You can sense an animal’s feelings and thoughts, and they can feel and act on yours.",
    ],
  },
  {
    label: "Etiquette",
    type: "eti",
    val: [
      "• You know how to address your local ruler without causing a faux pas.",
      "•• You know the rules of etiquette in each of the domain’s popular nightspots.",
      "••• You impress others with your command of politeness, deference, and grace.",
      "•••• Your behavior sets trends, especially if you do something to buck the norm of etiquette.",
      "••••• The Keeper of Elysium and the Harpies look to you to establish domain protocol.",
    ],
  },
  {
    label: "Insight",
    type: "ins",
    val: [
      "• You can see straight through hollow boasts.",
      "•• You pick up on the hidden emotion between humans and even sometimes between Kindred.",
      "••• You can provide psychotherapy even more effectively than someone who doesn’t want to eat their patient.",
      "•••• You are an undead lie detector. Only the best con artists can slip one by you.",
      "••••• People may be books of blood, but they are printed in very large type – easy to read.",
    ],
  },
  {
    label: "Intimidation",
    type: "int",
    val: [
      "• You can cut a scathing insult effectively.",
      "•• You can push your way around most humans without difficulty.",
      "••• Your swagger and your cruel behavior have earned you your reputation.",
      "•••• You're far past mere physical threats.",
      "••••• Even fellow Kindred may step back if you step up.",
    ],
  },
  {
    label: "Leadership",
    type: "lea",
    val: [
      "• You have led informal clubs before and can organize Kindred of like mind.",
      "•• Your voice makes itself heard in council, and even your superiors sometimes listen.",
      "••• You can command on the battlefield and lead your soldiers into death.",
      "•••• You can inspire the injured and dying to action, so long as you are there to lead them.",
      "••••• Your words fill a vampire’s heart with enough strength to make it feel alive and beating.",
    ],
  },
  {
    label: "Performance",
    type: "perf",
    val: [
      "• You are the life of the party, but you wouldn’t take your act on stage.",
      "•• You have performed for others, to mixed reviews. Some love you, others hate you.",
      "••• You are an expert student of your chosen performing art.",
      "•••• You perform your practiced art form stunningly, winning over even Toreador far and wide.",
      "••••• Improvisation holds no terrors for you: every night a different audience, every night a different show.",
    ],
  },
  {
    label: "Persuasion",
    type: "pers",
    val: [
      "• You can sell to a motivated buyer.",
      "•• You can always swing a discount or get on the inside track of the latest gossip.",
      "••• You can always figure out a compromise in a given conflict.",
      "•••• The other side starts looking for a settlement when they see you in court, human or Kindred.",
      "••••• You may be the original silver-tongued devil.",
    ],
  },
  {
    label: "Streetwise",
    type: "str",
    val: [
      "• You know where to score drugs and sex in your domain.",
      "•• You know which gangs operate in the area, including their colors and rivalries. You may have your own graffiti tag.",
      "••• You can tell the good shit from bad, score guns, and blend in seamlessly with street people or gangbangers.",
      "•••• When gangsters say “I know a guy,” you’re who they know.",
      "••••• You can hire, orchestrate, or arrange almost any criminal activity anywhere in your city.",
    ],
  },
  {
    label: "Subterfuge",
    type: "sub",
    val: [
      "• You can tell believable, simple lies.",
      "•• You can hustle naive people, old and young, into giving you their things.",
      "••• You can operate on multiple levels, telling lies intended to be uncovered to bolster other lies.",
      "•••• You can operate endlessly in deep cover: a perfect double agent. Perhaps you are!",
      "••••• Nobody believes you have even a single dot in Subterfuge.",
    ],
  },
  {
    label: "Academics",
    type: "aca",
    val: [
      "• Basic primary and secondary education; a night class at community college",
      "•• Basic university education or tutelage from a mediocre mentor; a four-year degree",
      "••• Advanced university education or dedicated personal tuition; an excellent four-year degree, a doctorate",
      "•••• Advanced specialized study beyond university, learning into subjects few understand",
      "••••• Refined and advanced scholarship, likely to be sought out for advice and tutelage",
    ],
  },
  {
    label: "Awareness",
    type: "awa",
    val: [
      "• You have a history of knowing when something is out of place.",
      "•• You can spot erratic or pattern behavior in an individual.",
      "••• You can see through most disguises and sense concealed dangers or hidden clues.",
      "•••• Even when you are distracted, few things are beyond your notice.",
      "••••• Your senses are those of a wild animal.",
    ],
  },
  {
    label: "Finance",
    type: "fin",
    val: [
      "• You can run a business and keep books.",
      "•• You can manage a corporate division or bank branch; you file impeccably plausible tax returns.",
      "••• Thanks to international trading, you make a fine broker on foreign stock exchanges.",
      "•••• Investment banks follow your financial lead. You have no trouble concealing fraud.",
      "••••• You can make money do anything, including stick to your pockets – or crash countries.",
    ],
  },
  {
    label: "Investigation",
    type: "inv",
    val: [
      "• You love a good mystery novel and fancy yourself an amateur sleuth.",
      "•• You have a firm knowledge of criminology and the signature acts of local rogues.",
      "••• You are, or could be, a detective by trade. Nothing in a crime scene escapes you.",
      "•••• The Sheriff comes to you when unknown parties sabotage the domain’s safety.",
      "••••• You set riddles for others and live an enigmatic existence few can penetrate.",
    ],
  },
  {
    label: "Medicine",
    type: "med",
    val: [
      "• You know basic anatomy and the difference in blood flow from a vein and an artery. You can perform CPR and other first aid. You may have been a medical student in life.",
      "•• You can comfortably treat minor traumas and illnesses and narrow down a diagnosis. You may have been a nurse or EMT in life.",
      "••• Your training allows you to perform major operations and treat serious injuries. You may have been an internist, pediatrician, or general practitioner in life.",
      "•••• You can diagnose and treat all but the rarest of illnesses. You may have been a surgeon or specialist in life.",
      "••••• You are a noted medical expert, sought out by mortals and immortals alike.",
    ],
  },
  {
    label: "Occult",
    type: "occ",
    val: [
      "• You know the legends of Caine and the Antediluvians, and you may have read the Book of Nod.",
      "•• You can sift the truth from pop occult nonsense.",
      "••• You have firsthand experience of something inexplicable, even by Kindred standards.",
      "•••• You could name most of the Antediluvians and even comprehend a Tremere ritual.",
      "••••• Tremere and Children of Haqim consult with you on obscure lore.",
    ],
  },
  {
    label: "Politics",
    type: "pol",
    val: [
      "• You follow mortal political affairs in your regnum, and you know at least what the elders reveal about Kindred politics.",
      "•• You can apply influence at a local level, or you know who can.",
      "••• You could run political campaigns or political machines, or make waves in your sect as an up-and-comer.",
      "•••• You know the true personalities of the real movers and shakers, live and undead, in your area.",
      "••••• You could guess at the unknown members of the Camarilla’s Inner Circle.",
    ],
  },
  {
    label: "Science",
    type: "sci",
    val: [
      "• You dabble in the sciences and understand the principles behind the building blocks of life.",
      "•• You can accurately explain the competing scientific theories of the Embrace to another vampire.",
      "••• You make an excellent scientific manager; you can run a laboratory, interpret scientific findings, and get up to speed on scientific research in most fields. You can repair scientific equipment.",
      "•••• You are an expert in your field and in those allied to it.",
      "••••• Few peers match your understanding, and others come to you for guidance.",
    ],
  },
  {
    label: "Technology",
    type: "tec",
    val: [
      "•  You know how to upgrade a home PC and keep it protected from viruses.",
      "•• You can conceal your IP, operate drones, and fake a digital photograph.",
      "••• You can create and unleash your own viruses without fear of detection.",
      "•••• The Prince might call you personally to manage cybersecurity for their domain.",
      "••••• On the internet, nobody knows you’re a vampire – or that you’re there at all.",
    ],
  },
];

export default skills;
